[package]
name = "rusti"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15.0"
serenity = { version = "0.12.2", features = [
    "framework",
    "cache",
    "model",
    "gateway",
] }
tokio = { version = "1.38.0", features = ["rt-multi-thread"] }
